services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 15432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.24.0
    ports:
      - 8081:8080
    environment:
      - SWAGGER_JSON=/openapi/openapi.yml
    volumes:
      - ./openapi:/openapi

volumes:
  postgres-volume:
