openapi: "3.1.1"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /todos:
    $ref: "./paths/todos.yml"
  /todos/{todoId}:
    $ref: "./paths/todos-id.yml"
  /categories:
    $ref: "./paths/categories.yml"
  /categories/{categoryId}:
    $ref: "./paths/categories-id.yml"
