openapi: "3.1.1"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /todos:
    get:
      summary: Todo一覧取得
      operationId: getTodos
      tags:
        - todos
      responses:
        "200":
          description: Todo一覧の取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
    post:
      summary: Todo作成
      operationId: createTodo
      tags:
        - todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoInput"
      responses:
        "201":
          description: Todo作成成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "400":
          description: 不正なリクエスト
  /todos/{todoId}:
    parameters:
      - name: todoId
        in: path
        required: true
        description: TodoのID
        schema:
          type: string
    get:
      summary: Todo詳細取得
      operationId: getTodoById
      tags:
        - todos
      responses:
        "200":
          description: Todo取得成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "404":
          description: Todoが見つかりません
    put:
      summary: Todo更新
      operationId: updateTodo
      tags:
        - todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoInput"
      responses:
        "200":
          description: Todo更新成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "400":
          description: 不正なリクエスト
        "404":
          description: Todoが見つかりません
    delete:
      summary: Todo削除
      operationId: deleteTodo
      tags:
        - todos
      responses:
        "204":
          description: Todo削除成功
        "404":
          description: Todoが見つかりません
components:
  schemas:
    Todo:
      type: object
      required:
        - id
        - title
        - completed
        - createdAt
      properties:
        id:
          type: string
          description: TodoのユニークID
          example: "550e8400-e29b-41d4-a716-446655440000"
        title:
          type: string
          description: Todoのタイトル
          example: "買い物に行く"
        description:
          type: string
          description: Todoの詳細説明
          example: "牛乳とパンを買う"
        completed:
          type: boolean
          description: 完了状態
          example: false
        createdAt:
          type: string
          format: date-time
          description: 作成日時
          example: "2024-01-15T09:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: 更新日時
          example: "2024-01-15T10:30:00Z"
    TodoInput:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Todoのタイトル
          example: "買い物に行く"
        description:
          type: string
          description: Todoの詳細説明
          example: "牛乳とパンを買う"
        completed:
          type: boolean
          description: 完了状態
          default: false
          example: false
